### ISSUE TITLE
Feature Request: Locked Roles

### ISSUE THREAD

**Issue by BeardCaliper** [Skillz4Killz/gamer-eris#614]
This feature request is similar to the Roleset feature, but instead of only allowing 1 role in a set, it requires a role in order to be able to have the other roles.
In order to get +role 1,2, or 3 you must have the required role. 

_For example:_
.lockrolesetcreate [name of set] [required role]
.lockrolesetadd [name of set] [+role]
.lockrolesetremove [name of set] [+role]
.lockrolesetdelete [name of set]

A lockroleset will make sure that a user can not obtain roles from that set without a trigger role. For example, if you have roles like platform roles for your games servers. You can create a roleset to make sure that a user can not pick up roles without the correlating platform.

**.lockrolesetcreate [name of set] [required Role]**~ Create a roleset on this server. Role names with spaces should be provided with their role id. To get the role id, use the .roleinfo command.

**.lockrolesetadd [name of set] [+role]** ~ Adds a requierd role to an existing lockroleset.
The lockroleset that you are trying to add the role to must already have been created with the .lockrolesetcreate command.

**.lockrolesetremove [name of set] [+role]** ~ Removes a role from an existing roleset.
The lockroleset that you are trying to remove the role from must already have been created with the .lockrolesetcreate command.

**.lockrolesetdelete [name of set]** ~ Deletes the roleset with the provided name on your server.

**Comment by Skillz4Killz** [comment]
I've personally built this and will be coming in the next update. No bounty rewarded for this as i've done it myself. @BeardCaliper Note however, i've changed the name from locked to `required` as the feature is basically a role is required for you to gain other roles.
